scanners:
  - "@continuous-security/scanner-javascript-js-x-ray"
  - "@continuous-security/scanner-javascript-njsscan"
  - "@continuous-security/scanner-javascript-npm-audit"
  - name: "@continuous-security/scanner-zed-attack-proxy"
    with:
      target: http://host.docker.internal:3000
